"""
Report Generator for Network Scanner Pro
Created by GhostCmd
"""

import json
import csv
import os
from datetime import datetime
from reportlab.lib.pagesizes import letter, A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.graphics.shapes import Drawing
from reportlab.graphics.charts.barcharts import VerticalBarChart
import matplotlib.pyplot as plt
import pandas as pd
from colorama import Fore, Style
import logging

class ReportGenerator:
    def __init__(self, config):
        self.config = config
        self.report_dir = "reports"
        self.create_report_directory()
    
    def create_report_directory(self):
        """Create reports directory if it doesn't exist"""
        if not os.path.exists(self.report_dir):
            os.makedirs(self.report_dir)
    
    def generate_pdf_report(self, results):
        """Generate comprehensive PDF report"""
        try:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"{self.report_dir}/network_scan_report_{timestamp}.pdf"
            
            doc = SimpleDocTemplate(filename, pagesize=A4)
            story = []
            styles = self.get_pdf_styles()
            
            # Title
            title_style = styles['Title']
            story.append(Paragraph("Network Security Assessment Report", title_style))
            story.append(Spacer(1, 12))
            
            # Header information
            story.append(Paragraph(f"Generated by: Network Scanner Pro", styles['Heading2']))
            story.append(Paragraph(f"Created by: GhostCmd", styles['Heading2']))
            story.append(Paragraph(f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", styles['Heading2']))
            story.append(Spacer(1, 20))
            
            # Executive Summary
            if self.config['report_settings']['include_executive_summary']:
                story.append(Paragraph("Executive Summary", styles['Heading1']))
                exec_summary = self.generate_executive_summary(results)
                story.append(Paragraph(exec_summary, styles['Normal']))
                story.append(Spacer(1, 12))
            
            # Network Discovery Results
            if 'network_discovery' in results:
                story.append(Paragraph("Network Discovery", styles['Heading1']))
                network_data = self.format_network_data(results['network_discovery'])
                if network_data:
                    network_table = Table(network_data, colWidths=[1.5*inch, 2*inch, 2*inch, 1*inch])
                    network_table.setStyle(TableStyle([
                        ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
                        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                        ('FONTSIZE', (0, 0), (-1, 0), 12),
                        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                        ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
                        ('GRID', (0, 0), (-1, -1), 1, colors.black)
                    ]))
                    story.append(network_table)
                    story.append(Spacer(1, 12))
            
            # Port Scanning Results
            if 'port_scanning' in results:
                story.append(Paragraph("Port Scanning Results", styles['Heading1']))
                port_data = self.format_port_data(results['port_scanning'])
                for target_data in port_data:
                    story.append(Paragraph(f"Target: {target_data['target']}", styles['Heading2']))
                    for protocol, ports in target_data['protocols'].items():
                        story.append(Paragraph(f"Protocol: {protocol.upper()}", styles['Heading3']))
                        if ports:
                            port_table = Table(ports, colWidths=[0.8*inch, 0.8*inch, 1.5*inch, 2*inch])
                            port_table.setStyle(TableStyle([
                                ('BACKGROUND', (0, 0), (-1, 0), colors.lightblue),
                                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                                ('GRID', (0, 0), (-1, -1), 1, colors.black)
                            ]))
                            story.append(port_table)
                            story.append(Spacer(1, 6))
            
            # Vulnerability Assessment
            if 'vulnerability_assessment' in results:
                story.append(Paragraph("Vulnerability Assessment", styles['Heading1']))
                vuln_data = self.format_vulnerability_data(results['vulnerability_assessment'])
                if vuln_data:
                    for severity, vulnerabilities in vuln_data.items():
                        story.append(Paragraph(f"{severity.upper()} Severity Vulnerabilities", styles['Heading2']))
                        for vuln in vulnerabilities:
                            story.append(Paragraph(f"• {vuln}", styles['Normal']))
                        story.append(Spacer(1, 6))
            
            # Charts and Statistics
            story.append(Paragraph("Scan Statistics", styles['Heading1']))
            stats = self.generate_statistics(results)
            for stat, value in stats.items():
                story.append(Paragraph(f"{stat}: {value}", styles['Normal']))
            
            # Build PDF
            doc.build(story)
            print(f"{Fore.GREEN}[+] PDF report generated: {filename}{Style.RESET_ALL}")
            return filename
            
        except Exception as e:
            logging.error(f"PDF report generation error: {str(e)}")
            return None
    
    def generate_html_report(self, results):
        """Generate interactive HTML report"""
        try:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"{self.report_dir}/network_scan_report_{timestamp}.html"
            
            html_content = f"""
            <!DOCTYPE html>
            <html lang="en">
            <head>
                <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <title>Network Security Assessment Report</title>
                <style>
                    body {{ font-family: Arial, sans-serif; margin: 40px; background-color: #f5f5f5; }}
                    .header {{ background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; border-radius: 10px; margin-bottom: 30px; }}
                    .section {{ background: white; padding: 20px; margin-bottom: 20px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }}
                    table {{ width: 100%; border-collapse: collapse; margin: 10px 0; }}
                    th, td {{ padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }}
                    th {{ background-color: #4CAF50; color: white; }}
                    tr:hover {{ background-color: #f5f5f5; }}
                    .critical {{ color: #ff4444; font-weight: bold; }}
                    .high {{ color: #ff8800; font-weight: bold; }}
                    .medium {{ color: #ffbb33; }}
                    .low {{ color: #00C851; }}
                    .stats {{ display: flex; justify-content: space-around; flex-wrap: wrap; }}
                    .stat-box {{ background: white; padding: 20px; margin: 10px; border-radius: 8px; box-shadow: 0 2px 5px rgba(0,0,0,0.1); text-align: center; min-width: 150px; }}
                </style>
            </head>
            <body>
                <div class="header">
                    <h1>Network Security Assessment Report</h1>
                    <p>Generated by Network Scanner Pro | Created by GhostCmd</p>
                    <p>Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
                </div>
            """
            
            # Executive Summary
            if self.config['report_settings']['include_executive_summary']:
                html_content += f"""
                <div class="section">
                    <h2>Executive Summary</h2>
                    <p>{self.generate_executive_summary(results)}</p>
                </div>
                """
            
            # Statistics
            stats = self.generate_statistics(results)
            html_content += """
            <div class="section">
                <h2>Scan Statistics</h2>
                <div class="stats">
            """
            for stat, value in stats.items():
                html_content += f"""
                    <div class="stat-box">
                        <h3>{value}</h3>
                        <p>{stat}</p>
                    </div>
                """
            html_content += """
                </div>
            </div>
            """
            
            # Network Discovery
            if 'network_discovery' in results:
                html_content += """
                <div class="section">
                    <h2>Network Discovery</h2>
                    <table>
                        <tr>
                            <th>IP Address</th>
                            <th>MAC Address</th>
                            <th>Vendor</th>
                            <th>Status</th>
                        </tr>
                """
                for host in results['network_discovery']:
                    status_class = "low" if host['status'] == 'up' else "medium"
                    html_content += f"""
                        <tr>
                            <td>{host['ip']}</td>
                            <td>{host['mac']}</td>
                            <td>{host['vendor']}</td>
                            <td class="{status_class}">{host['status'].upper()}</td>
                        </tr>
                    """
                html_content += """
                    </table>
                </div>
                """
            
            # Port Scanning
            if 'port_scanning' in results:
                html_content += """
                <div class="section">
                    <h2>Port Scanning Results</h2>
                """
                for target, data in results['port_scanning'].items():
                    html_content += f"""
                    <h3>Target: {target}</h3>
                    """
                    for protocol, ports in data.get('protocols', {}).items():
                        html_content += f"""
                        <h4>Protocol: {protocol.upper()}</h4>
                        <table>
                            <tr>
                                <th>Port</th>
                                <th>State</th>
                                <th>Service</th>
                                <th>Version</th>
                            </tr>
                        """
                        for port, info in ports.items():
                            state_class = "low" if info['state'] == 'open' else "medium"
                            html_content += f"""
                            <tr>
                                <td>{port}</td>
                                <td class="{state_class}">{info['state'].upper()}</td>
                                <td>{info['service']}</td>
                                <td>{info.get('version', '')}</td>
                            </tr>
                            """
                        html_content += """
                        </table>
                        """
                html_content += """
                </div>
                """
            
            # Vulnerabilities
            if 'vulnerability_assessment' in results:
                vuln_data = self.format_vulnerability_data(results['vulnerability_assessment'])
                html_content += """
                <div class="section">
                    <h2>Vulnerability Assessment</h2>
                """
                for severity, vulnerabilities in vuln_data.items():
                    severity_class = severity.lower()
                    html_content += f"""
                    <h3 class="{severity_class}">{severity.upper()} Severity Vulnerabilities</h3>
                    <ul>
                    """
                    for vuln in vulnerabilities:
                        html_content += f"<li>{vuln}</li>"
                    html_content += """
                    </ul>
                    """
                html_content += """
                </div>
                """
            
            html_content += """
            </body>
            </html>
            """
            
            with open(filename, 'w') as f:
                f.write(html_content)
            
            print(f"{Fore.GREEN}[+] HTML report generated: {filename}{Style.RESET_ALL}")
            return filename
            
        except Exception as e:
            logging.error(f"HTML report generation error: {str(e)}")
            return None
    
    def generate_csv_report(self, results):
        """Generate CSV report for data analysis"""
        try:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"{self.report_dir}/network_scan_report_{timestamp}.csv"
            
            with open(filename, 'w', newline='') as csvfile:
                writer = csv.writer(csvfile)
                
                # Write header
                writer.writerow(['Section', 'Target', 'Port', 'Protocol', 'Service', 'State', 'Vulnerability', 'Severity', 'Details'])
                
                # Network Discovery
                if 'network_discovery' in results:
                    for host in results['network_discovery']:
                        writer.writerow(['Network Discovery', host['ip'], '', '', '', host['status'], '', '', host['vendor']])
                
                # Port Scanning
                if 'port_scanning' in results:
                    for target, data in results['port_scanning'].items():
                        for protocol, ports in data.get('protocols', {}).items():
                            for port, info in ports.items():
                                writer.writerow(['Port Scan', target, port, protocol, info['service'], info['state'], '', '', info.get('version', '')])
                
                # Vulnerabilities
                if 'vulnerability_assessment' in results:
                    for vuln in results['vulnerability_assessment'].get('vulnerabilities', []):
                        details = vuln['details']
                        writer.writerow([
                            'Vulnerability',
                            vuln.get('service', ''),
                            vuln.get('port', ''),
                            vuln.get('protocol', ''),
                            '',
                            '',
                            details.get('issue', ''),
                            details.get('severity', ''),
                            details.get('details', '')
                        ])
            
            print(f"{Fore.GREEN}[+] CSV report generated: {filename}{Style.RESET_ALL}")
            return filename
            
        except Exception as e:
            logging.error(f"CSV report generation error: {str(e)}")
            return None
    
    def get_pdf_styles(self):
        """Get PDF styles"""
        styles = getSampleStyleSheet()
        
        # Custom styles
        styles.add(ParagraphStyle(
            name='CustomTitle',
            parent=styles['Title'],
            fontSize=24,
            spaceAfter=30,
            textColor=colors.darkblue
        ))
        
        return styles
    
    def format_network_data(self, network_results):
        """Format network data for PDF table"""
        data = [['IP Address', 'MAC Address', 'Vendor', 'Status']]
        for host in network_results:
            data.append([
                host['ip'],
                host['mac'],
                host['vendor'],
                host['status'].upper()
            ])
        return data
    
    def format_port_data(self, port_results):
        """Format port data for PDF"""
        formatted_data = []
        for target, data in port_results.items():
            target_data = {
                'target': target,
                'protocols': {}
            }
            for protocol, ports in data.get('protocols', {}).items():
                protocol_data = [['Port', 'State', 'Service', 'Version']]
                for port, info in ports.items():
                    protocol_data.append([
                        str(port),
                        info['state'].upper(),
                        info['service'],
                        info.get('version', '')
                    ])
                target_data['protocols'][protocol] = protocol_data
            formatted_data.append(target_data)
        return formatted_data
    
    def format_vulnerability_data(self, vuln_results):
        """Format vulnerability data"""
        by_severity = {}
        for vuln in vuln_results.get('vulnerabilities', []):
            severity = vuln['details'].get('severity', 'unknown')
            if severity not in by_severity:
                by_severity[severity] = []
            
            vuln_text = f"{vuln['type']} - {vuln['service']} on port {vuln['port']}: {vuln['details'].get('issue', 'Unknown issue')}"
            if 'cve_id' in vuln['details']:
                vuln_text += f" ({vuln['details']['cve_id']})"
            
            by_severity[severity].append(vuln_text)
        
        return by_severity
    
    def generate_executive_summary(self, results):
        """Generate executive summary"""
        total_hosts = len(results.get('network_discovery', []))
        open_ports = 0
        vulnerabilities = len(results.get('vulnerability_assessment', {}).get('vulnerabilities', []))
        
        if 'port_scanning' in results:
            for target, data in results['port_scanning'].items():
                for protocol, ports in data.get('protocols', {}).items():
                    open_ports += len([p for p in ports.values() if p['state'] == 'open'])
        
        summary = f"""
        This network security assessment discovered {total_hosts} active hosts with {open_ports} open ports. 
        The vulnerability assessment identified {vulnerabilities} potential security issues requiring attention.
        """
        
        if vulnerabilities > 0:
            summary += " Immediate remediation is recommended for high and critical severity vulnerabilities."
        else:
            summary += " No critical vulnerabilities were identified during this assessment."
        
        return summary
    
    def generate_statistics(self, results):
        """Generate scan statistics"""
        stats = {}
        
        # Network stats
        stats['Hosts Discovered'] = len(results.get('network_discovery', []))
        
        # Port stats
        open_ports = 0
        if 'port_scanning' in results:
            for target, data in results['port_scanning'].items():
                for protocol, ports in data.get('protocols', {}).items():
                    open_ports += len([p for p in ports.values() if p['state'] == 'open'])
        stats['Open Ports'] = open_ports
        
        # Vulnerability stats
        vuln_count = len(results.get('vulnerability_assessment', {}).get('vulnerabilities', []))
        stats['Vulnerabilities Found'] = vuln_count
        
        # Services scanned
        services_scanned = results.get('vulnerability_assessment', {}).get('services_scanned', 0)
        stats['Services Scanned'] = services_scanned
        
        return stats
    
    def generate_reports(self, results, output_format="all"):
        """Generate all requested reports"""
        report_paths = {}
        
        if output_format in ["pdf", "all"] and self.config['report_settings']['generate_pdf']:
            report_paths['pdf'] = self.generate_pdf_report(results)
        
        if output_format in ["html", "all"] and self.config['report_settings']['generate_html']:
            report_paths['html'] = self.generate_html_report(results)
        
        if output_format in ["csv", "all"] and self.config['report_settings']['generate_csv']:
            report_paths['csv'] = self.generate_csv_report(results)
        
        return report_paths